repository: ethereum/go-ethereum

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore

google_analytics: UA-131485733-1
favicon: /static/images/favicon.png

defaults:
  -
    scope:
      path: docs
    values:
      layout: sidebar